### ISSUE TITLE
'Struct' object has no attribute 'hands_componentsl'

### ISSUE THREAD

**Issue by arwooy** [athn-nik/teach#24]
After download the data from https://mano.is.tue.mpg.de/download.php,  get the SMPLH_MALE.pkl from mano_v1_2.zip, and put it to smpl_models dir.
When I run the demo interact_teach.py, got the following error:

Traceback (most recent call last):
  File "/root/miniconda3/envs/teach-env/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 62, in _call_target
    return _target_(*args, **kwargs)
  File "/root/autodl-tmp/github/teach/teach/transforms/rots2joints/smplh.py", line 58, in __init__
    self.smplh = SMPLHLayer(path, ext="pkl", gender=gender).eval()
  File "/root/miniconda3/envs/teach-env/lib/python3.9/site-packages/smplx/body_models.py", line 761, in __init__
    super(SMPLHLayer, self).__init__(
  File "/root/miniconda3/envs/teach-env/lib/python3.9/site-packages/smplx/body_models.py", line 601, in __init__
    left_hand_components = data_struct.hands_componentsl[:num_pca_comps]
AttributeError: 'Struct' object has no attribute 'hands_componentsl'

**Comment by atnikos** [comment]
Hey,
Can you please follow the steps described here? To have the correct smplh model?
https://github.com/athn-nik/teach/issues/2
I.e. the one for amass which is merged smpl with Mano?

**Comment by arwooy** [comment]
Thanks a lot,  I follow this steps, and get the smplh model,   but a new error happened

Traceback (most recent call last):
  File "/root/miniconda3/envs/teach-env/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 62, in _call_target
    return _target_(*args, **kwargs)
  File "/root/autodl-tmp/github/teach/teach/transforms/rots2joints/smplh.py", line 58, in __init__
    self.smplh = SMPLHLayer(path, ext="pkl", gender=gender).eval()
  File "/root/miniconda3/envs/teach-env/lib/python3.9/site-packages/smplx/body_models.py", line 761, in __init__
    super(SMPLHLayer, self).__init__(
  File "/root/miniconda3/envs/teach-env/lib/python3.9/site-packages/smplx/body_models.py", line 590, in __init__
    super(SMPLH, self).__init__(
  File "/root/miniconda3/envs/teach-env/lib/python3.9/site-packages/smplx/body_models.py", line 142, in __init__
    shapedirs = data_struct.shapedirs
AttributeError: 'Struct' object has no attribute 'shapedirs'

**Comment by arwooy** [comment]
Thanks a lot. it can execute completed without error report and looks like success. But when I check the output dir, It's empty

Global seed set to 1234
[27/11/22 07:02:21][__main__][INFO] - Loading model
[27/11/22 07:02:21][torch.distributed.nn.jit.instantiator][INFO] - Created a temporary directory at /tmp/tmpd2r8cg3s
[27/11/22 07:02:21][torch.distributed.nn.jit.instantiator][INFO] - Writing /tmp/tmpd2r8cg3s/_remote_module_non_sriptable.py
[27/11/22 07:02:22][__main__][INFO] - Model 'teach' loaded
[27/11/22 07:02:25][__main__][INFO] - Model weights restored
Global seed set to 0

**Comment by atnikos** [comment]
Can you give me the exact command you are running? In my computer, the output seems to be created fine.

**Comment by arwooy** [comment]
I tested two cases.  
python interact_teach.py folder=./teach output=./output texts='[A person walks to the lake, picks up stones on the ground, and fetches them into the water]' durs='[10, 10, 10]'
python interact_teach.py folder=./teach output=./output texts='[walk, sit down, wave hands, drink water, stand up]' durs='[5,5,5,5,5]'

**Comment by atnikos** [comment]
Can you check the current directory? Or provide with an extra `/` the output directory?

**Comment by arwooy** [comment]
Thanks, I found it in current dir, filename is output_sample-0.mp4
