### ISSUE TITLE
AssertionError: Path /path/to/teach/data/smpl_models/smpl/SMPL_MALE.pkl does not exist!

### ISSUE THREAD

**Issue by haosome6** [athn-nik/teach#42]
I followed the instructions and made the SMPLH_MALE.pkl inside /teach/data/smpl_models/smplh/ as suggested. 
But I still got the following error:

> python interact_teach.py folder=/path/to/teach/experiment output=/path/to/teach/results texts='[sit down, walk to the left, stand still]' durs='[5, 5, 3]'

Global seed set to 1234
[10/07/23 10:19:44][__main__][INFO] - Loading model
[10/07/23 10:19:44][torch.distributed.nn.jit.instantiator][INFO] - Created a temporary directory at /tmp/tmpvf0vd9d2
[10/07/23 10:19:44][torch.distributed.nn.jit.instantiator][INFO] - Writing /tmp/tmpvf0vd9d2/_remote_module_non_sriptable.py
[10/07/23 10:19:46][__main__][INFO] - Model 'teach' loaded
[10/07/23 10:19:48][__main__][INFO] - Model weights restored
Global seed set to 0
Error executing job with overrides: ['folder=/path/to/teach/experiment', 'output=/path/to/teach/results', 'texts=[sit down, walk to the left, stand still]', 'durs=[5, 5, 3]']
Traceback (most recent call last):
  File "/path/to/teach/interact_teach.py", line 35, in _interact
    return interact(cfg)
  File "/path/to/teach/interact_teach.py", line 103, in interact
    vid_ = visualize_meshes(motion)
  File "/path/to/teach/teach/render/mesh_viz.py", line 77, in visualize_meshes
    smpl = get_body_model(path=f'{get_original_cwd()}/data/smpl_models',
  File "/path/to/teach/teach/utils/smpl_body_utils.py", line 116, in get_body_model
    body_model = smplx.create(body_model_path, model_type=type,
  File "/path/to/.conda/envs/teach-env/lib/python3.9/site-packages/smplx/body_models.py", line 2400, in create
    return SMPL(model_path, **kwargs)
  File "/path/to/.conda/envs/teach-env/lib/python3.9/site-packages/smplx/body_models.py", line 133, in __init__
    assert osp.exists(smpl_path), 'Path {} does not exist!'.format(
AssertionError: Path /path/to/data/smpl_models/smpl/SMPL_MALE.pkl does not exist!

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

However, if I copy the SMPLH_MALE.pkl, rename it as SMPL_MALE.pkl, and put it under /teach/data/smpl_models/smpl. It seems working. I just wonder if this is the correct way to handle it. Thank you.

**Comment by atnikos** [comment]
Thanks for spotting this :)
You are actually very correct. I will test and fix this tomorrow and get back to you here. Since we don't use any hand articulation it doesn't really matter, but for to keep the code alive and clean it needs to be fixed 💪
